### ISSUE TITLE
New firewall resource always thinks changes need to be made.

### ISSUE THREAD

**Issue by carrete** [terraform-providers/terraform-provider-digitalocean#30]
Hi,

I've noticed a problem with the outbound rule in the new firewall resource. `terraform apply` wants to modify this outbound rule every time where instead it should say no changes need to be made.

### Terraform Version
    $ terraform -version
    Terraform v0.10.0

### Affected Resource(s)
 - digitalocean_firewall

### Terraform Configuration Files
See also: https://gitlab.com/tvaughan/terraform-digitalocean-starterkit/blob/master/firewalls.tf
```hcl
# -*- coding: utf-8; mode: terraform -*-

resource "digitalocean_firewall" "starterkit_firewall" {
  name = "allow-outbound-ssh-http-https"

  droplet_ids = [
    "${digitalocean_droplet.starterkit_droplet.id}",
  ]

  inbound_rule = [
    {
      protocol   = "tcp"
      port_range = "22"

      source_addresses = [
        "0.0.0.0/0",
        "::/0",
      ]
    },
    {
      protocol   = "tcp"
      port_range = "80"

      source_addresses = [
        "0.0.0.0/0",
        "::/0",
      ]
    },
    {
      protocol   = "tcp"
      port_range = "443"

      source_addresses = [
        "0.0.0.0/0",
        "::/0",
      ]
    },
  ]

  outbound_rule = [
    {
      protocol   = "tcp"
      port_range = "all"

      destination_addresses = [
        "0.0.0.0/0",
        "::/0",
      ]
    },
    {
      protocol   = "udp"
      port_range = "53"  # DNS

      destination_addresses = [
        "0.0.0.0/0",
        "::/0",
      ]
    },
  ]
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Terraform should say that no changes need to be made if this plan is run more than once.

### Actual Behavior
Terraform repeatedly tries to update the outbound rule:

    ~ digitalocean_firewall.starterkit_firewall
        outbound_rule.0.port_range: "53" => "all"
        outbound_rule.0.protocol:   "udp" => "tcp"
        outbound_rule.1.port_range: "0" => "53"
        outbound_rule.1.protocol:   "tcp" => "udp"

If I look at the firewall in my DigitalOcean dashboard I see that everything has already been created correctly.

### Steps to Reproduce
    terraform apply

### Important Factoids
None that I can think of.

### References
Not that I was able to find. I looked for dupes.

**Comment by dghubble** [comment]
I see this behavior as well as terraform trying to always update the `port_range`.

```
      inbound_rule.3.port_range:  "0" => "all"
      inbound_rule.4.port_range:  "0" => "all"
      outbound_rule.1.port_range: "0" => "all"
      outbound_rule.2.port_range: "0" => "all"
```

 The firewall resource type seems have issues with using a stable sort of the list of rules and with comparing its string values (like "all") with what the DO API will return on subsequent requests.

**Comment by simonwydooghe** [comment]
I can confirm this behaviour, I have the following resource:

```
resource "digitalocean_firewall" "vuilbak" {
  name = "vuilbak"
  droplet_ids = ["${digitalocean_droplet.vuilbak.id}"]

  inbound_rule = [
    {
      protocol         = "icmp"
      source_addresses = ["0.0.0.0/0"]
    },
    {
      protocol         = "tcp"
      port_range       = "22"
      source_addresses = ["0.0.0.0/0"]
    }
  ]

  outbound_rule = [
    {
      protocol              = "icmp"
      destination_addresses = ["0.0.0.0/0"]
    },
    {
      protocol              = "tcp"
      port_range            = "all"
      destination_addresses = ["0.0.0.0/0"]
    },
    {
      protocol              = "udp"
      port_range            = "all"
      destination_addresses = ["0.0.0.0/0"]
    }
  ]
}
```

terraform plan on a subsequent run with no code changes reports the following:
```
  ~ digitalocean_firewall.vuilbak
      inbound_rule.0.port_range:  "22" => ""
      inbound_rule.0.protocol:    "tcp" => "icmp"
      inbound_rule.1.port_range:  "0" => "22"
      inbound_rule.1.protocol:    "icmp" => "tcp"
      outbound_rule.0.port_range: "0" => ""
      outbound_rule.0.protocol:   "tcp" => "icmp"
      outbound_rule.1.port_range: "0" => "all"
      outbound_rule.1.protocol:   "udp" => "tcp"
      outbound_rule.2.port_range: "0" => "all"
      outbound_rule.2.protocol:   "icmp" => "udp"
```

It seems like it simply wants to switch the order of the rules around.

**Comment by BrianHicks** [comment]
I'm getting the same behavior with the same version. I've found that I can deal with shuffling the rules around to however it ends up sorting them after I make a change (it is *stable*, if not exactly *predictable*) but sill am having trouble with the `"0" => "all"` lines.

**Comment by danrabinowitz** [comment]
It looks like the `"0" => "all"` issue is fixed by this PR: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/41

That should be released in the next release of terraform-provider-digitalocean, version 0.1.3.

**Comment by pschirch** [comment]
This issue still exists.

```
Terraform v0.11.3
+ provider.digitalocean v0.1.3
```
Create a new firewall works.

```
resource "digitalocean_tag" "default-firewall" {
  name = "Default-Firewall"
}

resource "digitalocean_firewall" "default-firewall" {
  name = "Default-Firewall"

  tags = ["${digitalocean_tag.default-firewall.id}"]

  inbound_rule = [
    {
      protocol         = "tcp"
      port_range       = "22"
      source_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]

  outbound_rule = [
    {
      protocol              = "icmp"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol              = "tcp"
      port_range            = "all"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol              = "udp"
      port_range            = "all"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]
}
```
But if you run `terraform plan` next time Terraform wants to change firewall configuration although there are no changes.

```
Terraform will perform the following actions:

  ~ digitalocean_firewall.default-firewall
      outbound_rule.0.port_range: "0" => ""
```
This results in an error if you want run `terraform apply` for changes that are really wanted.

```
* digitalocean_firewall.default-firewall: Error updating firewall: PUT https://api.digitalocean.com/v2/firewalls/525e50a2-ad47-44a8-8bcd-52c7dc8ebab5: 422 (request "3d967ce0-cf0d-4a8b-912d-a1a9625e5a3a") You must specify a positive value for ports.
```

Any updates on this issue?

**Comment by pschirch** [comment]
Same error occurs if you want to add the ICMP rule to an existing firewall.

Create a new firewall.

```
resource "digitalocean_tag" "default-firewall" {
  name = "Default-Firewall"
}

resource "digitalocean_firewall" "default-firewall" {
  name = "Default-Firewall"

  tags = ["${digitalocean_tag.default-firewall.id}"]

  inbound_rule = [
    {
      protocol         = "tcp"
      port_range       = "22"
      source_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]

  outbound_rule = [
    {
      protocol              = "tcp"
      port_range            = "all"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    {
      protocol              = "udp"
      port_range            = "all"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
  ]
}
```
Now let's say you forgot the ICMP rule and want to add it.

```
outbound_rule = [
    {
      protocol              = "icmp"
      destination_addresses = ["0.0.0.0/0", "::/0"]
    },
    ...
  ]
```
```
* digitalocean_firewall.default-firewall: Error updating firewall: PUT https://api.digitalocean.com/v2/firewalls/525e50a2-ad47-44a8-8bcd-52c7dc8ebab5: 422 (request "433d0f00-bf77-4992-b90b-1e7ed7981650") You must specify a positive value for ports.
```
Any advice?

**Comment by F00b4rch** [comment]
Working for me by doing this : 

```
  outbound_rule = [
    {
      protocol = "tcp"
      port_range = "all"
      destination_addresses = [
        "0.0.0.0/0",
        "::/0"]
    },
    {
      protocol = "udp"
      port_range = "all"
      destination_addresses = [
        "0.0.0.0/0",
        "::/0"]
    },
    {
      protocol = "icmp"
      port_range = "1-65535"
      destination_addresses = [
        "0.0.0.0/0",
        "::/0"]
    },
  ]
```

I know it's a bit weird, but it's the only way I've found to make it works.

Hope it helps !

**Comment by pschirch** [comment]
@F00b4rch In case you create a completely new firewall and do not change the ICMP rule definition this workaround helps. But in case yout want to edit a firewall, e.g. to add or delete the ICMP rule an error ouccurs as well.

```
* digitalocean_firewall.default-firewall: Error updating firewall: PUT https://api.digitalocean.com/v2/firewalls/f8ddaabe-7190-4d60-9b7d-2f24af010e43: 422 (request "5415d903-c8e8-4e14-a346-9b9e44198571") You must specify a positive value for ports.
```

**Comment by pschirch** [comment]
This error also occurs if you editing a firewall that initially have a ICMP rule defined. So actually you can not seriously manage a Digital Ocean firewall with Terraform. Unfortunately an unsatisfactory condition.

**Comment by z3ntu** [comment]
In my opinion an example for ICMP should be listed in the docs.

**Comment by andrewsomething** [comment]
I'm happy to say that yesterday, we release version 1.0.0 of the DigitalOcean Terraform provider. It should include a fix for this issue.

You can find the full changelog here: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/CHANGELOG.md#100-september-27-2018

In order to upgrade an existing project to the latest version, run:

```
terraform init -upgrade
```

If you believe that this issue is being closed by mistake or the problem has not been resolved, please let me know or feel free to open a new issue with additional details.

Thanks for your patience!
